apiVersion: apps/v1
kind: Deployment
metadata:
  name:  active-mq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: active-mq
  template:
    metadata:
      labels:
        app: active-mq
    spec:
      containers:
        - name: active-mq
          image: rmohr/activemq
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
            requests:
              memory: 128Mi
              cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: active-mq
  labels:
    app: active-mq
spec:
  selector:
    app: active-mq
  ports:
    - name: dashboard
      port: 8161
      targetPort: 8161
      protocol: TCP
    - name: openwire
      port: 61616
      targetPort: 61616
      protocol: TCP
  type: LoadBalancer
